"""initial schema

Revision ID: 1ec52d4cc707
Revises: 
Create Date: 2025-05-20 00:42:13.209588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ec52d4cc707'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id_cliente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('apellido', sa.String(length=255), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_table('partes',
    sa.Column('id_parte', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_parte', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('costo', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id_parte'),
    sa.UniqueConstraint('numero_parte')
    )
    op.create_table('vehiculos',
    sa.Column('id_vehiculo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('año', sa.Integer(), nullable=True),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_vehiculo'),
    sa.UniqueConstraint('vin')
    )
    op.create_table('ordenes_de_reparacion',
    sa.Column('id_orden', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('mano_de_obra', sa.Float(), nullable=False),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculos.id_vehiculo'], ),
    sa.PrimaryKeyConstraint('id_orden')
    )
    op.create_table('detalles_orden',
    sa.Column('id_detalle', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_orden', sa.Integer(), nullable=False),
    sa.Column('id_parte', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_orden'], ['ordenes_de_reparacion.id_orden'], ),
    sa.ForeignKeyConstraint(['id_parte'], ['partes.id_parte'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalles_orden')
    op.drop_table('ordenes_de_reparacion')
    op.drop_table('vehiculos')
    op.drop_table('partes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
